version: '3'

tasks:
  default:
    cmds:
      - task: errs
      - task: zapobject
      - task: test
      - task: nancy

  test:
    desc: Test and lint.
    cmds:
      - go test -shuffle on ./...
      - go test -shuffle on ./zapobject/...
      - govulncheck ./...
      - govulncheck ./zapobject/...
      - docker run --rm -v $(pwd):/app -w /app golangci/golangci-lint:v1.51.1 golangci-lint run --enable gosec --timeout 3m0s ./...
    sources:
      - ./go.mod
      - '**/*.go'

  nancy:
    desc: Check vulnerability of external packages with Nancy.
    cmds:
      - depm list -j | nancy sleuth -n
    sources:
      - ./go.mod
      - '**/*.go'

  clean:
    desc: Initialize module and build cache.
    cmds:
      - go clean -cache
      - go clean -modcache

  errs:
    cmds:
      - rm -f ./go.sum
      - go mod tidy -v -go=1.20

  zapobject:
    dir: zapobject
    cmds:
      - rm -f ./go.sum
      - go mod tidy -v -go=1.20
