version: '3'

tasks:
  default:
    cmds:
      - task: errs
      - task: zapobject
      - task: test
      - task: govulncheck
      # - task: nancy

  test:
    desc: Test and lint.
    cmds:
      - go test -shuffle on ./...
      - go test -shuffle on ./zapobject/...
      - govulncheck ./...
      - govulncheck ./zapobject/...
      - golangci-lint-v2 run --enable gosec --timeout 3m0s ./...
    sources:
      - ./go.mod
      - '**/*.go'

  govulncheck:
    desc: Check reachable vulnerabilities with latest govulncheck.
    cmds:
      - go run golang.org/x/vuln/cmd/govulncheck@latest ./...
    sources:
      - ./go.mod
      - '**/*.go'

  nancy:
    desc: Check vulnerability of external packages with Nancy.
    cmds:
      - depm list -j | nancy sleuth -n
    sources:
      - ./go.mod
      - '**/*.go'

  clean:
    desc: Initialize module and build cache.
    cmds:
      - go clean -cache
      - go clean -modcache

  errs:
    cmds:
      - rm -f ./go.sum
      - go mod tidy -v -go=1.20

  zapobject:
    dir: zapobject
    cmds:
      - rm -f ./go.sum
      - go mod tidy -v -go=1.20
